name: CI

on:
  push:
    branches: ["feature/build-deploy"]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 20.x.0

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

        - uses: actions/upload-pages-artifact@v2
          with:
            path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v3
        id: deployment
