name: CI

on:
  push:
    branches: ["feature/github-pages-deploy"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          mkdir build
          echo "<h1>Hello GitHub Pages!</h1>" > build/index.html
      - uses: actions/upload-artifact@v3
        with:
          name: demo_site
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
